services:
  api:
    build:
      context: .
      target: prod
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
    ports:
      - "${API_PORT:-3000}:3000"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:17.4-alpine3.21
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-nest_task3_db}
    volumes:
      - db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.2.4-management-alpine
    restart: unless-stopped
    hostname: message-broker
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-password}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  db_data:
  rabbitmq_data:
